package dev.modplugin.reputationban.config;

import java.util.Map;
import java.util.List;

public record ConfigValidationInput(
        int initialScore,
        int maxScore,
        int minReasonLength,
        int minUniqueReportsBeforeDeduction,
        int reportWindowDays,
        int globalReportSeconds,
        int sameTargetCooldownDays,
        int maxReportsPerDay,
        int maxReportsPerWeek,
        int minPlaytimeMinutes,
        int minAccountAgeDays,
        int banThreshold,
        int recoveryPointsPerDay,
        int recoveryMaxScore,
        int recoveryNoReportDaysRequired,
        int auditMaxDisplayLimit,
        int auditMaxExportLimit,
        int retentionAuditEventsDays,
        int retentionRejectedReportsDays,
        int retentionCancelledReportsDays,
        int retentionScoreHistoryDays,
        int retentionBansDays,
        int discordWebhookTimeoutSeconds,
        String auditExportDirectory,
        double luckPermsDefaultWeight,
        Map<String, Double> luckPermsGroupWeights,
        int coreProtectMinimumApiVersion,
        int coreProtectLookupSeconds,
        int coreProtectRadius,
        int coreProtectMaxResults,
        int worldGuardMaxRegions,
        List<String> worldGuardReportContextCategories,
        List<String> griefPreventionReportContextCategories,
        List<String> discordSrvAccountLinkContextCategories,
        String placeholderApiIdentifier,
        int placeholderApiCacheRefreshSeconds
) {
    public static ConfigValidationInput from(PluginConfig config) {
        return new ConfigValidationInput(
                config.initialScore(),
                config.maxScore(),
                config.minReasonLength(),
                config.minUniqueReportsBeforeDeduction(),
                config.reportWindowDays(),
                config.globalReportSeconds(),
                config.sameTargetCooldownDays(),
                config.maxReportsPerDay(),
                config.maxReportsPerWeek(),
                config.minPlaytimeMinutes(),
                config.minAccountAgeDays(),
                config.banThreshold(),
                config.recoveryPointsPerDay(),
                config.recoveryMaxScore(),
                config.recoveryNoReportDaysRequired(),
                config.auditMaxDisplayLimit(),
                config.auditMaxExportLimit(),
                config.retentionAuditEventsDays(),
                config.retentionRejectedReportsDays(),
                config.retentionCancelledReportsDays(),
                config.retentionScoreHistoryDays(),
                config.retentionBansDays(),
                config.discordWebhookConfig().timeoutSeconds(),
                config.auditExportDirectory(),
                config.luckPermsIntegration().defaultWeight(),
                config.luckPermsIntegration().groupWeights(),
                config.coreProtectIntegration().minimumApiVersion(),
                config.coreProtectIntegration().lookupSeconds(),
                config.coreProtectIntegration().radius(),
                config.coreProtectIntegration().maxResults(),
                config.worldGuardIntegration().maxRegions(),
                config.worldGuardIntegration().reportContextCategories(),
                config.griefPreventionIntegration().reportContextCategories(),
                config.discordSrvIntegration().accountLinkContextCategories(),
                config.placeholderApiIntegration().identifier(),
                config.placeholderApiIntegration().cacheRefreshSeconds()
        );
    }
}
